package flags

var (
	// CleanUpTidy ...
	CleanUpTidy bool
	// CleanUpDryRun ...
	CleanUpDryRun bool
	// CleanupForce ...
	CleanupForce bool
	// CleanupDelivered ...
	CleanupDelivered bool
	// RootInit ...
	RootInit bool
	// RootInit ...
	RootVersion bool
)
