name: Repo Report

on:
  push:
    branches:
      - '*' 
jobs:
  report:
    name: Report
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
          
    - name: Get Repo script
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        mkdir -p /usr/local/reporeport
        gh clone lakruzz/reporeport --depth 1 /usr/local/reporeport
        ls -a /usr/local/reporeport
