name: Repo Report

on:
  push:
    branches:
      - '*' 
jobs:
  report:
    name: Report
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
          
    - name: Get and run reporeport script
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        gh repo clone lakruzz/reporeport ~/.reporeport -- --depth 1
        ~/.reporeport/reporeport --full_name ${{github.repository}}
